### ISSUE TITLE
Unable to Configure Drives for Teams, Stats

### ISSUE THREAD

**Issue by jfarney66** [jleonard2099/LHG_ProBB#18]
Hi:

I am using Ver 4.3 of Lance Haffner Basketball: The Pro Game. When I open the screen from the Main Menu, I get a gray screen. I have attached a screenshot. I have also copied the 80-81 NBA teams file and schedule file in the root where Hello.exe is. I unable to see those teams when I try to play a game.

Also, is there any way to mazimize the screen, or should I just change resolution seetings when playing?

Thanks for your time and effort on this! This is a HUGE plus over DOSBox if I can get it running correctly on my PC.

John
![LHBBTPG Issue](https://user-images.githubusercontent.com/127785651/224800400-7da6523f-6986-43c7-ae2a-c26f9bfdc6e9.png)

**Comment by jleonard2099** [comment]
You can change the screen mode by pressing Alt+ENTER at the same time.

The only time I've seen the "gray screen" like that is if CAPS LOCK is on or pressed when using the screen for Configuring Drives.

I have traced the code for that and do not understand why it happens,.

Let me know if this helps.

**Comment by jfarney66** [comment]
Hi Jason:

Thank you very much! Those suggestions worked. Thanks again for the time and effort on this! This is a huge benfit to be able to play these games hatively in Windows.

John Farney
